#!/bin/bash

. /lib/lsb/init-functions

SERVICE_NAME='mcs-sch'
EXEC_USER='op1'
EXEC_PATH='/home/op1/MCS/sch'

check_self() {
	output=`service $SERVICE_NAME status`
	if [ "$output" != "not running" ]; then
		log_action_msg "$SERVICE_NAME appears to be running" || true
		exit 0
	fi
}

start() {
	log_daemon_msg "Starting MCS/sch"
	logfile=`tempfile -p mcs-sch-`
	if su $EXEC_USER -c "cd $EXEC_PATH && ./start_station.sh" > $logfile 2>&1; then
		log_end_msg 0 || true
	else
		log_end_msg 1 || true
		cat $logfile
	fi
	rm -f $logfile
}

stop() {
	log_daemon_msg "Stopping MCS/sch"
	logfile=`tempfile -p mcs-sch-`
	if su $EXEC_USER -c "cd $EXEC_PATH && ./ms_shutdown.sh" > $logfile 2>&1; then
		log_end_msg 0 || true
	else
		log_end_msg 1 || true
		cat $logfile
	fi
	rm -f $logfile
}

status() {
	output=`ps aux | grep ms_ | grep -v grep`
	if [ "$output" != "" ]; then
		procs=`echo "$output" | awk '{print $2}' | sed -e ':a;{N;s/\n/ /;ba}' `
		echo "$SERVICE_NAME start/running, processes $procs"
	else
		echo "not running"
	fi
}

wait_socket_clear() {
	log_daemon_msg "Waiting 60s for sockets to clear"
	sleep 60
	log_end_msg 0 || true
}

case "$1" in
	start)
		check_self
		start
		;;
	stop)
		stop
		;;
	status)
		status
		;;
	restart|reload)
		stop
		wait_socket_clear
		start
		;;
	*)
		echo $"Usage $0 {start|stop|restart|reload|status}"
		exit 1
esac

exit 0
