#!/bin/bash

### BEGIN INIT INFO
# Provides:        mcs-exec
# Required-Start:  $network mcs-sch
# Required-Stop:   none
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start the the mcs executive
### END INIT INFO

. /lib/lsb/init-functions

SERVICE_NAME='mcs-exec'
EXEC_USER='op1'
EXEC_PATH='/home/op1/MCS/exec'

check_self() {
	output=`service $SERVICE_NAME status`
	if [ "$?" == "0" ]; then
		log_action_msg "$SERVICE_NAME appears to be running" || true
		exit 0
	fi
}

check_mcs_sch() {
	output=`service mcs-sch status`
	if [ "$output" == "not running" ]; then
		log_action_msg "mcs-sch does not appear to be running" || true
		log_end_msg 1 || true
		exit 0
	fi
}

start() {
	log_daemon_msg "Starting MCS/exec"
	check_mcs_sch
	logfile=`tempfile -p mcs-exec-`
	if su $EXEC_USER -c "cd $EXEC_PATH && ./me_init 0" > $logfile 2>&1; then
		log_end_msg 0 || true
	else
		log_end_msg 1 || true
		cat $logfile
	fi
	rm -f $logfile
}

stop() {
	log_daemon_msg "Stopping MCS/exec"
	logfile=`tempfile -p mcs-exec-`
	if su $EXEC_USER -c "cd $EXEC_PATH && ./meeix SHT" > $logfile 2>&1; then
		log_end_msg 0 || true
	else
		log_end_msg 1 || true
		cat $logfile
	fi
	rm -f $logfile
}

status() {
	output=`ps aux | grep me_ | grep -v grep`
	if [ "$output" != "" ]; then
		procs=`echo "$output" | awk '{print $2}' | sed -e ':a;{N;s/\n/ /;ba}' `
		echo "$SERVICE_NAME start/running, processes $procs"
	else
		echo "not running"
	fi
}

wait_socket_clear() {
	log_daemon_msg "Waiting 60s for sockets to clear"
	sleep 60
	log_end_msg 0 || true
}

case "$1" in
	start)
		check_self
		start
		;;
	stop)
		stop
		;;
	status)
		status
		;;
	restart|reload)
		stop
		wait_socket_clear
		start
		;;
	*)
		echo $"Usage $0 {start|stop|restart|reload|status}"
		exit 1
esac

exit 0
