name: "Build and Test"
on: [push, pull_request, release]
jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "release", "workflow_dispatch", "schedule"]'
  build:
    needs: pre_build
    if: ${{ needs.pre_build.outputs.should_skip != 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.10', '3.12']
      fail-fast: false
    steps:
      - name: "Software Install - Ubuntu"
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install -y \
            build-essential \
            ca-certificates \
            coreutils \
            curl \
            git \
            gpg \
            gpgv \
            gzip \
            libcurl4-openssl-dev \
            libfftw3-dev \
            libgdbm-dev \
            libgsl-dev \
            pkg-config \
            software-properties-common
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: "Software Install - Python" 
        run: |
          python -m pip install \
            setuptools \
            numpy \
            astropy \
            ephem \
            requests
      - name: "Software Install - Python, Part 2" 
        run: |
          python -m pip install lsl
      - name: "Build and Install"
        run: |
          ./configure --with-sch-ip=127.0.0.1
          make all
          mkdir -p exec/state
      - name: Test - Scheduler
        run: |
          cd sch/tests
          python -m unittest discover
      - name: Test - Executive
          cd $GITHUB_WORKSPACE
          cd exec/tests
          python -m unittest discover
